In [7]:
library(data.table)

In [8]:
#Data cleaning was completed using Open Refine. Look at doc x for more details
cigarette_data <- fread("episode-5-data-exploration/cigarette-consumption.csv")
cigarette_data

    Month     Year # of cigarettes sold # of cigarettes produced
1   January   2004 2,932,197            2,586,972
2   February  2004 2,675,718            2,535,635
3   March     2004 3,208,140            3,154,586
4   April     2004 3,107,788            2,992,174
5   May       2004 3,185,678            3,241,380
6   June      2004 3,772,473            3,334,575
7   July      2004 2,562,059            3,345,682
8   August    2004 3,238,115            3,444,878
9   September 2004 3,694,043            3,272,152
10  October   2004 3,388,046            3,366,947
11  November  2004 3,801,400            2,711,863
12  December  2004 2,345,731            3,286,900
13  January   2005 2,967,012            2,600,130
14  February  2005 3,071,744            2,729,526
15  March     2005 3,364,751            2,914,081
16  April     2005 3,610,165            2,821,311
17  May       2005 3,004,348            3,129,694
18  June      2005 3,423,538            3,510,770
19  July      2005 3,073,654            3,160,294
20  August    2005 3,224,215            3,464,834
21  September 2005 3,282,396            3,175,082
22  October   2005 3,465,835            2,863,755
23  November  2005 3,140,783            3,205,976
24  December  2005 2,654,662            3,441,805
25  January   2006 2,302,406            2,243,835
26  February  2006 2,778,209            2,479,568
27  March     2006 2,499,460            2,343,905
28  April     2006 2,280,742            2,179,266
29  May       2006 2,160,048            2,570,828
30  June      2006 2,334,257            2,447,757
... ...       ...  ...                  ...
162 June      2017 1,925,349            1,796,520
163 July      2017 1,673,252            1,787,128
164 August    2017 1,846,273            2,033,892
165 September 2017 1,655,521            1,752,771
166 October   2017 1,970,745            1,763,759
167 November  2017 2,175,761            1,624,214
168 December  2017 1,166,840            1,932,982
169 January   2018 1,548,314A           1,325,425A
170 February  2018 1,509,441A           1,383,982A
171 March     2018 1,850,556A,r         1,667,976A,r
172 April     2018 1,664,500A           1,568,080A
173 May       2018 1,822,172A           2,002,748A
174 June      2018 1,608,183A           1,785,998A
175 July      2018 1,831,275A           1,802,864A
176 August    2018 1,832,769A           1,999,349A
177 September 2018 1,677,927A           1,502,671A
178 October   2018 2,072,293A           1,712,575A
179 November  2018 2,067,643A           1,690,928A
180 December  2018 1,388,125A           1,645,486A
181 January   2019 1,840,209A           1,277,868A
182 February  2019 1,831,299A           1,272,727A
183 March     2019 2,066,253A           1,448,145A
184 April     2019 1,852,158A           1,543,485A
185 May       2019 1,833,948A           1,768,760A
186 June      2019 1,666,877B           1,559,943B
187 July      2019 1,763,322A           1,699,265A
188 August    2019 1,402,511A           1,735,092A
189 September 2019 1,920,866A           1,494,682A
190 October   2019 1,872,788A           1,590,038A
191 November  2019 1,816,321A           1,779,303A
    # of cigarettes in opening inventory # of cigarettes in closing inventory
1   3,411,355                            3,415,754
2   3,415,754                            3,569,334
3   3,569,334                            3,808,825
4   3,809,094                            4,013,915
5   4,013,915                            4,035,835
6   4,035,835                            4,324,218
7   4,324,218                            3,584,438
8   3,584,438                            3,497,206
9   3,497,207                            3,635,042
10  3,635,042                            3,595,264
11  3,595,264                            4,465,496
12  4,465,496                            3,318,167
13  3,318,197                            3,722,837
14  3,722,837                            3,974,254
15  3,974,254                            4,575,499
16  4,575,499                            5,030,731
17  5,030,731                            5,060,559
18  5,060,559                            5,078,404
19  5,078,404                            4,585,413
20  4,585,413                            4,612,529
21  4,610,753                            4,751,867
22  4,751,867                            5,056,485
23  5,056,485                            5,147,538
24  5,147,538                            4,003,933
25  4,003,933                            4,081,505
26  4,081,505                            3,951,096
27  3,951,096                            3,860,410
28  3,860,410                            3,442,773
29  3,442,773                            2,906,337
30  2,906,337                            2,208,923
... ...                                  ...
162 null                                 null
163 null                                 null
164 null                                 null
165 null                                 null
166 null                                 null
167 null                                 null
168 null                                 null
169 null                                 2,428,330A
170 2,428,330A                           2,532,735A
171 2,532,735A,r                         2,656,258A,r
172 2,656,258A                           2,729,107A
173 2,729,107A                           null
174 null                                 2,313,523A
175 2,313,523A                           null
176 null                                 2,052,182A
177 2,052,182A                           null
178 null                                 2,247,421A
179 2,247,421A                           null
180 null                                 2,104,486A
181 2,104,486A                           null
182 null                                 2,873,923A
183 2,873,923A                           null
184 null                                 3,430,198A
185 3,430,198A                           null
186 null                                 3,436,156B
187 3,436,156B                           null
188 null                                 2,744,401A
189 2,744,401A                           null
190 null                                 3,052,711A
191 3,052,711A                           null